main: net.wytrem.spigot.philios.Philios
name: Philios
version: 1.0
author: wytrem
api-version: "1.14"
commands:
  friend:
    description: Manage friendships
    usage: /friend <ask|remove|>
    permission: philios.use
permissions:
  philios.use:
    description: Allows to use /friend
    default: true
