name: @name@
main: @mainPackage@.@name@
version: @version@
api-version: @apiVersion@
description: @description@
author: @author@
website: @website@
commands:
  friend:
    description: Manage friendships
    usage: /friend <ask|remove|>
    permission: philios.use
permissions:
  philios.use:
    description: Allows to use /friend
    default: true
